version: '3.5'

services:
  bigfoot_host:
    build: 
      context: ./
      dockerfile: Host.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../basic_mobile_robot:/ros_ws/src/basic_mobile_robot
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #privileged: true
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t