version: '3.5'

services:
  basic_mobile_robot:
    build: 
      context: ./
      dockerfile: BigfootDescription.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ros_ws/src/bigfoot_description # wee ned it to be able to update package source inside the container (for development)
      #- ../:/bigfoot
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #privileged: true
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t