ARG BASE_IMAGE="nvcr.io/nvidia/isaac/ros:aarch64-humble-nav2_c2befe2b1d90532fc15ef72650ccd7b0"
FROM ${BASE_IMAGE} 

# Zero interaction while installing or upgrading the system via apt. 
# It accepts the default answer for all questions.
ENV DEBIAN_FRONTEND=noninteractive

ENV ROS_WS=/ros2_ws
#WORKDIR $ROS_WS

# -- Build RealSense SDK from sources
# https://github.com/jetsonhacks/installRealSenseSDK
COPY docker/scripts/build-librealsense.sh /opt/realsense/build-librealsense.sh
COPY docker/scripts/install-realsense-dependencies.sh /opt/realsense/install-realsense-dependencies.sh

#RUN chmod +x /opt/realsense/install-realsense-dependencies.sh && /opt/realsense/install-realsense-dependencies.sh
#RUN chmod +x /opt/realsense/build-librealsense.sh && /opt/realsense/build-librealsense.sh
# === end of block 'install RealSense SDK'

# === Setup entrypoint
COPY docker/ros_entrypoint.sh /

# Change workdir
#WORKDIR /root/ros2_ws

# [] - is exec form
# exec form vs shell form - the difference is whether the specified command is invoked inside a shell or not
# Exec - runs the process directly (not inside a shell) (doesn't create separate process to run a command/program)
# So shell process with PID 1 is replaced by the process of running program in exec mode
#ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
