# --- Parameters file for the package 'teleop_twist_joy'
#
# 'teleop_node' - node that republishes sensor_msgs/msg/Joy messages 
# as scaled geometry_msgs/msg/Twist messages.

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.59
    scale_linear_turbo:
      x: 1.59

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 7.0

    enable_button: 4  # L1 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
    require_enable_button : false