#version: '3.5' # version flag is Depricated?

services:
  bigfootbot:
    #restart: unless-stopped

    image: humble_realsense:latest

    #build: 
     # context: ..
     # dockerfile: docker/Dockerfile.aarch64.humble.nav2.realsense

    #container_name: webcam
    #working_dir: /webcam

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # forward X socket to container to enable GUI 
      #- ./cyclonedds.xml:/cyclonedds.xml # for Husarnet VPN

    # Enable GPU access for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    runtime: nvidia

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      #- HTTP_PORT=81 # This means our app1 will listen on port 81 inside **Husarnet's** network namespace
      #- DEBUG_HTTP=true
      #- DEBUG_SERVER=true
      #- DEBUG_CLIENT=true
    
    privileged: true # To allow container to access RealSense camera (USB) on the host
    #devices:
    #  - /dev:/dev
    
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #pid: host
    #ipc: host

    # This section makes your app1 move into the namespace of Husarnet.
    # This means you no longer can configure ports and other networking settings here
    # and all of those configs need to be moved to declaration of service `husarnet`.
    # This will also wait on Husarnet to actually start before starting your app
    network_mode: host

  # Test app (Web server)
  test_app:
    image: nginx
    
    volumes:
      - ./test_html:/usr/share/nginx/html

    network_mode: host

    # Published ports are discarded when using host network mode               
    #ports:
    #  - "80:80"
    
      