#version: '3.5' # version flag is Depricated in Docker compose V2?
services:
  humble_rviz2:
    #restart: unless-stopped
    
    build: 
      context: ..
      dockerfile: docker/Dockerfile.rviz2

    # The name of the Docker image to be created from the Dockerfile.
    image: humble_rviz2:latest

    # The name to be given to the container created from the image.
    container_name: humble_rviz2_container

    volumes:
      # Forward X socket to container to enable GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - DISPLAY=$DISPLAY  # To allow the container to access the host's 
                          # X11 server for GUI applications.
      #- QT_X11_NO_MITSHM=1 # To prevent Qt applications from crashing (bug fix)

    # Enable GPU access for the container NB! Only for NVIDIA GPUs
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          capabilities: [gpu]

    #runtime: nvidia
    
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    #command: ros2 launch /path/to/new_bfb_teleop_launch_file.launch
    
    #networks:
    #  bfb_network:

    network_mode: host
