#version: '3.5' # version flag is Depricated in Docker compose V2?

services:
  bigfootbot_drive:
    #restart: unless-stopped

    #image: humble_realsense:latest

    build: 
      context: ..
      dockerfile: docker/Dockerfile.aarch64.humble.nav2.bigfootbot_drive

    #container_name: webcam
    #working_dir: /webcam

    volumes:
      # forward X socket to container to enable GUI 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
      # Roboclaw motor driver config file. It is added as volume to be able to change motor driver parameters 
      # on the fly in the running container
      - ../bigfootbot_base/config/roboclaw_config.yaml:/ros2_ws/install/bigfootbot_base/share/bigfootbot_base/config/roboclaw_config.yaml                                                       

    # Enable GPU access for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    runtime: nvidia

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    
    privileged: true # To allow container to access RealSense camera (USB) on the host
    #devices:
    #  - /dev:/dev
    
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    network_mode: host

   ####################  BIGFOOTBOT REALSENSE ################
  bigfootbot_realsense:
    #restart: unless-stopped

    #image: humble_realsense:latest

    build: 
      context: ..
      dockerfile: docker/Dockerfile.aarch64.humble.nav2_bigfootbot_realsense

    #container_name: webcam
    #working_dir: /webcam

    #volumes:
      # forward X socket to container to enable GUI 
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
      # Roboclaw motor driver config file. It is added as volume to be able to change motor driver parameters 
      # on the fly in the running container
     # - ../bigfootbot_base/config/roboclaw_config.yaml:/ros2_ws/install/bigfootbot_base/share/bigfootbot_base/config/roboclaw_config.yaml                                                       

    # Enable GPU access for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    runtime: nvidia

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    
    privileged: true # To allow container to access RealSense camera (USB) on the host
    #devices:
    #  - /dev:/dev
    
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    network_mode: host

  # Test app (Web server)
  #test_app:
   # image: nginx
    
    #volumes:
   #   - ./test_html:/usr/share/nginx/html

   # network_mode: host

    # Published ports are discarded when using host network mode               
    #ports:
    #  - "80:80"
    
      