version: '3.5'

services:
  bigfootbot_description:
    build: 
      context: ./
      dockerfile: BigfootDescription.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # forward X socket to container to enable GUI 
      - ./:/ros_ws/src/bigfootbot_description # we need it to be able to update package source inside the container (for development)
      - ./cyclonedds.xml:/cyclonedds.xml # for Husarnet VPN
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #privileged: true
    #network_mode: host
    #pid: host
    #ipc: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    # Without custom DDS configuration file it would be simply command: 
    # ros2 run my_demo_pkg color_controller. 
    # Construction:
    # command:
    #  - bash
    #  - -c
    #  - |
    #    <multiple command, every in a new line>
    # allows you to easily run a few additional commands while starting a container.
    command:
      - bash
      - -c
      - |
          export CYCLONEDDS_URI=file:///cyclonedds.xml   
          ros2 launch bigfootbot_description bigfootbot_description.launch.py use_rviz:='False' use_simulator:='True'
       #   ros2 run my_demo_pkg color_controller
    network_mode: service:husarnet
  
  # Husarnet VPN
  husarnet:
    image: husarnet/husarnet:latest
    
    restart: unless-stopped
    
    volumes:
      # This will persist your Husarnet Client keys, thus IP of the container
      # will be stable/the same between (re)boots.
      # Feel free to choose any volume storage method of your liking
      - ./husarnet-config:/var/lib/husarnet

    # This is required to create new interface for communication over Husarnet
    cap_add:
      - NET_ADMIN
    
    # Husarnet is using IPv6 for it's overlay network so we need to make sure
    # it's not disabled
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    devices:
        - /dev/net/tun
    env_file: 
        - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there

  husarnet:
    

    
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

    # See `Shared environment variables` section
    environment:
      - HUSARNET_HOSTNAME=my-app-deployment
      - HUSARNET_JOIN_CODE=UcofxnS3MzGo69poeuA94Q
      - HUSARNET_DEBUG=1

    # As your apps are now running in Husarnet's container network namespace,
    # you need to move all the usual networking-related declarations here
    ports:
      - "8081:81"  # for app1
      - "8082:82"  # for app2