# docker run -it  --rm -p 1935:1935 --device=/dev/video0:/dev/video0 --name video-stream-container video-stream
# docker run -it -e "TERM=xterm-256color" --rm -p 1935:1935 --name rtmp_nginx_as_base_container rtmp_nginx_as_base - run in interactive mode

# Use NGINX base image with RTMP module
FROM nginx:latest

# Install necessary tools
RUN apt-get update && \
    apt-get install -y ffmpeg

# Copy nginx.conf with RTMP module configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the RTMP port
EXPOSE 1935

# Start NGINX when the container starts
#CMD ["nginx", "-g", "daemon off;"]
CMD ["bash"]