version: '3.5'

services:
  bigfoot_rpi:
    #privileged: true - allow access to host
    #devices: ["/dev/ttyACM0:/dev/ttyACM0"]    
    devices:
     #- /dev/input/js0:/dev/input/js0
     - /dev/input:/dev/input

    #TODO! access roboclaw by id (/dev/serial/by-id/usb-03eb_USB_Roboclaw_2x15A-if00)
    volumes:
      - ./launch/teleop-launch.py:/ros_ws/install/teleop_twist_joy/share/teleop_twist_joy/launch/teleop-launch.py
    # - /dev:/dev
    #build: .
    build: 
      context: ./
      dockerfile: RPi.Dockerfile
    
    #user: "${UID}:${GID}"

    #image: osrf/ros:foxy-desktop
    #command: ros2 run demo_nodes_cpp talker
    #volumes:
    #    - ./cyclonedds.xml:/cyclonedds.xml 
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #network_mode: service:husarnet
    network_mode: host

  #ros2:
   # image: ros:foxy
    #volumes:
     # - ./ros2_packages:/ros2_ws/src
    
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
