<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- ********************** ROBOT BASE AND BASE FOOTPRINT *********************************  -->

  <xacro:macro name="base" params="length width height mass wheel_radius wheel_zoff">

    <!-- Define the center of the main robot chassis projected on the ground -->	
    <link name="base_footprint"/>

    <!-- The base footprint of the robot is located underneath the chassis -->
    <joint name="base_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link" />
      <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
      <visual>
        <origin xyz="${length/2} ${-width/2} ${-height/2}" rpy="0 0 1.57079632679"/>
        <geometry>
          <!--box size="${length} ${width} ${height}"/-->
          <mesh filename="package://bigfootbot_description/meshes/frame_with_covers_2_m.stl" scale="1.0 1.0 1.0"/> <!-- scale="0.001 0.001 0.001"-->
          
          <!--mesh filename="file://$(find bigfootbot_description)/meshes/frame_with_covers_2_m.stl" scale="1.0 1.0 1.0"/--> <!-- scale="0.001 0.001 0.001"-->
          <!-- file:// is used instead on package:// because URDF->SDF converter converts package:// to model:// and Gazebo can't fint STLs -->
        </geometry>
        <material name="Red"/> <!-- Material for RViz-->
      </visual>

      <collision>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="${mass}" w="${width}" d="${length}" h="${height}"/> 
    </link>

    <gazebo reference="base_link">  
      <visual>  
        <material> <!-- Red material for Gazebo -->
          <ambient>1.0 0.0 0.0 1.0</ambient> <!-- RGB [0..1] + alpha [0..1]-->
          <diffuse>1.0 0.0 0.0 1.0</diffuse>
          <specular>0.0 0.0 0.0 1.0</specular>
          <emissive>0.0 0.0 0.0 1.0</emissive>
        </material>
      </visual> 
    </gazebo>

    <!--gazebo reference="base_link">
      <material>Gazebo/Red</material>
    </gazebo-->
  </xacro:macro>

</robot>