version: '3.5'

services:
  bigfootbot_description:
    build: 
      context: ./
      dockerfile: BigfootDescription.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # forward X socket to container to enable GUI 
      - ./:/ros_ws/src/bigfootbot_description # we need it to be able to update package source inside the container (for development)
      #- ../:/bigfoot
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #privileged: true
    #network_mode: host
    #pid: host
    #ipc: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t